Repository klasinky/karmaland-api, pull requests merged in 2022-10, with the labels that each got.

#3 :pushpin: | Adding check_youtube_user function
  settings.py
  utils/constants.py
  utils/request.py
Labels: hacktoberfest

#5 :pushpin: | refactor check_youtube_user function
  schemas/channels.py
  utils/constants.py
  utils/request.py
Labels: enhancement, good first issue, hacktoberfest

#6 :gear: | test check_youtube_user function
  README.md
  requirements.txt
  utils/request.py
  utils/tests.py
Labels: enhancement, good first issue, hacktoberfest

#7 :gear: | Resolving errors in tests
  utils/tests.py
Labels: good first issue, hacktoberfest

#9 Implementing redis
  .env.example
  api.py
  config/db.py
  config/redis.py
  redis_client/__init__.py
  redis_client/connection.py
  routes/channels.py
  schemas/channels.py
  settings.py
  utils/request.py
Labels: hacktoberfest

#10 Added redis to requirements and fix set function in connection.py
  redis_client/connection.py
  requirements.txt
  routes/channels.py
Labels: hacktoberfest, hacktoberfest-accepted
